#!/bin/bash

sbatch -p compute modflow_base_soil-compaction.sh
sbatch -p compute modflow_base.sh
sbatch -p compute modflow_base_soil-compaction_irrigation.sh
sbatch -p compute modflow_base_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_base_irrigation_yellow-mustard.sh
sbatch -p compute modflow_base_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_base_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_soil-compaction_irrigation.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_soil-compaction_irrigation.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_soil-compaction_irrigation_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-wet_soil-compaction.sh
sbatch -p compute modflow_spring-summer-wet.sh
sbatch -p compute modflow_spring-summer-wet_soil-compaction_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-wet_yellow-mustard.sh
sbatch -p compute modflow_spring-summer-wet_soil-compaction_grain-corn-only.sh
