name: roger-modflow

channels:
    - conda-forge

dependencies:
    - python=3.12
    - pip
    - click
    - pyyaml
    - entrypoints
    - numpy
    - scipy
    - pandas
    - loguru
    - tqdm
    - cython
    - h5netcdf
    - h5py
    - matplotlib
    - seaborn
    - cftime
    - flopy
    - xarray
    - geoxarray
    - rasterio
    - pyproj
    - netCDF4
    - xmipy
    - xesmf
    - shapely
    - geopandas
    - gstools
    - scikit-learn
    - pip:
        - jax
        - matplotlib-map-utils
