dict_obs_flow_rnos:
  DREI1_FLOW: 460
  DREI2_FLOW: 493
  DREI3_FLOW: 513
  DREI4_FLOW: 721
  DREI5_FLOW: 807
  DREI7_FLOW: 8957
  E2_FLOW: 662
  E4_FLOW: 741
  E6_FLOW: 828
  E8_FLOW: 857
  EBNET_FLOW: 872
  K1_FLOW: 397
  MOE2_FLOW: 7655
  MOE3_FLOW: 7705
  MOE4_FLOW: 7760
  MOE5_FLOW: 7791
  MOE6_FLOW: 8556
  NEU2_FLOW: 5822
  NEU3_FLOW: 6956
  OBERAMBRINGEN_FLOW: 4946
  RO2_A_FLOW: 273
  RO2_B_FLOW: 275
  W3_FLOW: 205
  W4_FLOW: 366
  WIESNECK_FLOW: 190
dict_obs_stage_rnos:
  DREI1_STAGE: 460
  DREI2_STAGE: 493
  DREI3_STAGE: 513
  DREI4_STAGE: 721
  DREI5_STAGE: 807
  DREI7_STAGE: 8957
  E2_STAGE: 662
  E4_STAGE: 741
  E6_STAGE: 828
  E8_STAGE: 857
  EBNET_STAGE: 872
  K1_STAGE: 397
  MOE2_STAGE: 7655
  MOE3_STAGE: 7705
  MOE4_STAGE: 7760
  MOE5_STAGE: 7791
  MOE6_STAGE: 8556
  NEU2_STAGE: 5822
  NEU3_STAGE: 6956
  OBERAMBRINGEN_STAGE: 4946
  RO2_A_STAGE: 273
  RO2_B_STAGE: 275
  W3_STAGE: 205
  W4_STAGE: 366
  WIESNECK_STAGE: 190
dx: 50.0
dy: 50.0
nx: 621
ny: 777
nz: 4
outlet_rnos:
- 25089
- 24974
- 24993
- 25030
- 24831
- 24712
- 24994
sfr_obs:
  DREI1_area:
  - wet-area
  - 460
  DREI1_depth:
  - depth
  - 460
  DREI1_flow:
  - downstream-flow
  - 460
  DREI1_stage:
  - stage
  - 460
  DREI2_area:
  - wet-area
  - 493
  DREI2_depth:
  - depth
  - 493
  DREI2_flow:
  - downstream-flow
  - 493
  DREI2_stage:
  - stage
  - 493
  DREI3_area:
  - wet-area
  - 513
  DREI3_depth:
  - depth
  - 513
  DREI3_flow:
  - downstream-flow
  - 513
  DREI3_stage:
  - stage
  - 513
  DREI4_area:
  - wet-area
  - 721
  DREI4_depth:
  - depth
  - 721
  DREI4_flow:
  - downstream-flow
  - 721
  DREI4_stage:
  - stage
  - 721
  DREI5_area:
  - wet-area
  - 807
  DREI5_depth:
  - depth
  - 807
  DREI5_flow:
  - downstream-flow
  - 807
  DREI5_stage:
  - stage
  - 807
  DREI7_area:
  - wet-area
  - 8957
  DREI7_depth:
  - depth
  - 8957
  DREI7_flow:
  - downstream-flow
  - 8957
  DREI7_stage:
  - stage
  - 8957
  E2_area:
  - wet-area
  - 662
  E2_depth:
  - depth
  - 662
  E2_flow:
  - downstream-flow
  - 662
  E2_stage:
  - stage
  - 662
  E4_area:
  - wet-area
  - 741
  E4_depth:
  - depth
  - 741
  E4_flow:
  - downstream-flow
  - 741
  E4_stage:
  - stage
  - 741
  E6_area:
  - wet-area
  - 828
  E6_depth:
  - depth
  - 828
  E6_flow:
  - downstream-flow
  - 828
  E6_stage:
  - stage
  - 828
  E8_area:
  - wet-area
  - 857
  E8_depth:
  - depth
  - 857
  E8_flow:
  - downstream-flow
  - 857
  E8_stage:
  - stage
  - 857
  Ebnet_area:
  - wet-area
  - 872
  Ebnet_depth:
  - depth
  - 872
  Ebnet_flow:
  - downstream-flow
  - 872
  Ebnet_stage:
  - stage
  - 872
  K1_area:
  - wet-area
  - 397
  K1_depth:
  - depth
  - 397
  K1_flow:
  - downstream-flow
  - 397
  K1_stage:
  - stage
  - 397
  MOE2_area:
  - wet-area
  - 7655
  MOE2_depth:
  - depth
  - 7655
  MOE2_flow:
  - downstream-flow
  - 7655
  MOE2_stage:
  - stage
  - 7655
  MOE3_area:
  - wet-area
  - 7705
  MOE3_depth:
  - depth
  - 7705
  MOE3_flow:
  - downstream-flow
  - 7705
  MOE3_stage:
  - stage
  - 7705
  MOE4_area:
  - wet-area
  - 7760
  MOE4_depth:
  - depth
  - 7760
  MOE4_flow:
  - downstream-flow
  - 7760
  MOE4_stage:
  - stage
  - 7760
  MOE5_area:
  - wet-area
  - 7791
  MOE5_depth:
  - depth
  - 7791
  MOE5_flow:
  - downstream-flow
  - 7791
  MOE5_stage:
  - stage
  - 7791
  MOE6_area:
  - wet-area
  - 8556
  MOE6_depth:
  - depth
  - 8556
  MOE6_flow:
  - downstream-flow
  - 8556
  MOE6_stage:
  - stage
  - 8556
  NEU2_area:
  - wet-area
  - 5822
  NEU2_depth:
  - depth
  - 5822
  NEU2_flow:
  - downstream-flow
  - 5822
  NEU2_stage:
  - stage
  - 5822
  NEU3_area:
  - wet-area
  - 6956
  NEU3_depth:
  - depth
  - 6956
  NEU3_flow:
  - downstream-flow
  - 6956
  NEU3_stage:
  - stage
  - 6956
  Oberambringen_area:
  - wet-area
  - 4946
  Oberambringen_depth:
  - depth
  - 4946
  Oberambringen_flow:
  - downstream-flow
  - 4946
  Oberambringen_stage:
  - stage
  - 4946
  RO2_A_area:
  - wet-area
  - 273
  RO2_A_depth:
  - depth
  - 273
  RO2_A_flow:
  - downstream-flow
  - 273
  RO2_A_stage:
  - stage
  - 273
  RO2_B_area:
  - wet-area
  - 275
  RO2_B_depth:
  - depth
  - 275
  RO2_B_flow:
  - downstream-flow
  - 275
  RO2_B_stage:
  - stage
  - 275
  W3_area:
  - wet-area
  - 205
  W3_depth:
  - depth
  - 205
  W3_flow:
  - downstream-flow
  - 205
  W3_stage:
  - stage
  - 205
  W4_area:
  - wet-area
  - 366
  W4_depth:
  - depth
  - 366
  W4_flow:
  - downstream-flow
  - 366
  W4_stage:
  - stage
  - 366
  Wiesneck_area:
  - wet-area
  - 190
  Wiesneck_depth:
  - depth
  - 190
  Wiesneck_flow:
  - downstream-flow
  - 190
  Wiesneck_stage:
  - stage
  - 190
