#!/bin/bash

sbatch -p compute modflow_base-magnitude0-duration0_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_base-magnitude0-duration0_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude0_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration0_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_no-irrigation_yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-drought_magnitude2_duration3_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
sbatch -p compute modflow_spring-summer-wet-magnitude0-duration0_no-irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-wet-magnitude0-duration0_no-irrigation_no-yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-wet-magnitude0-duration0_irrigation_no-yellow-mustard_soil-compaction.sh
sbatch -p compute modflow_spring-summer-wet-magnitude0-duration0_no-irrigation_yellow-mustard_no-soil-compaction.sh
sbatch -p compute modflow_spring-summer-wet-magnitude0-duration0_no-irrigation_no-yellow-mustard_soil-compaction_grain-corn-only.sh
