#!/bin/bash

sbatch -p compute calculate_annual_anomalies_dmn_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_hausen_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_zartener_becken_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_boetzingen_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_breisach_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_ebringen_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_eichstetten_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_gottenheim_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_krozinger_berg_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_march_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_schlatt_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_tuniberg_modflow.sh
sbatch -p compute calculate_annual_anomalies_wsg_umkirch_modflow.sh
