dx: 50  # grid spacing in x direction [m]
dy: 50  # grid spacing in y direction [m]
nx: 621  # number of grid cells in x direction
ny: 777  # number of grid cells in y direction
nz: 4   # number of grid layers


# !this part below is only needed if SFR package is used!
# identify outlet reach numbers by opening the shapefile "sfr_lines.shp" in QGIS
# "sfr_lines.shp" is produced by "write_sfr_data.py"
# Outlet reach numbers
outlet_rnos:
  - 25089
  - 24976
  - 24993
  - 25030
  - 24831
  - 24712
  - 24994

# reach numbers of streamflow and water observation points
# observation point can be identified by opening the shapefile "sfr_lines.shp" in QGIS
dict_obs_stage_rnos: 
  FALKENSTEIG_STAGE: 6695
  EBNET_STAGE: 14068
  EHRENKIRCHEN_STAGE: 21470
  MUENSTERTAL_STAGE: 14511

dict_obs_flow_rnos:
  FALKENSTEIG_FLOW: 6695
  EBNET_FLOW: 14068
  EHRENKIRCHEN_FLOW: 21470
  MUENSTERTAL_FLOW: 14511

sfr_obs:
  falkensteig_stage:
      - stage
      - 6695
  ebnet_stage:
      - stage
      - 14068
  ehrenkirchen_stage:
      - stage
      - 21470
  muenstertal_stage:
      - stage
      - 14511
  falkensteig_flow:
      - downstream-flow
      - 6695
  ebnet_flow:
      - downstream-flow
      - 14068
  ehrenkirchen_flow:
      - downstream-flow
      - 21470
  muenstertal_flow:
      - downstream-flow
      - 14511
