dx: 50  # grid spacing in x direction [m]
dy: 50  # grid spacing in y direction [m]
nx: 621  # number of grid cells in x direction
ny: 777  # number of grid cells in y direction
nz: 4   # number of grid layers


# !this part below is only needed if SFR package is used!
# identify outlet reach numbers by opening the shapefile "sfr_lines.shp" in QGIS
# "sfr_lines.shp" is produced by "write_sfr_data.py"
# Outlet reach numbers
outlet_rnos:
  - 25088
  - 24953
  - 24971
  - 25030
  - 24810
  - 24671
  - 24973

# reach numbers of streamflow and water observation points
# observation point can be identified by opening the shapefile "sfr_lines.shp" in QGIS
dict_obs_stage_rnos: 
  FALKENSTEIG_STAGE: 6188
  EBNET_STAGE: 13562
  EHRENKIRCHEN_STAGE: 21130
  MUENSTERTAL_STAGE: 14006

dict_obs_flow_rnos:
  FALKENSTEIG_FLOW: 6188
  EBNET_FLOW: 13562
  EHRENKIRCHEN_FLOW: 21130
  MUENSTERTAL_FLOW: 14006

sfr_obs:
  falkensteig_stage:
      - stage
      - 6188
  ebnet_stage:
      - stage
      - 13562
  ehrenkirchen_stage:
      - stage
      - 21130
  muenstertal_stage:
      - stage
      - 14006
  falkensteig_flow:
      - downstream-flow
      - 6188
  ebnet_flow:
      - downstream-flow
      - 13562
  ehrenkirchen_flow:
      - downstream-flow
      - 21130
  muenstertal_flow:
      - downstream-flow
      - 14006
